# Generated by Django 3.0.8 on 2020-10-13 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizpost',
            name='correct_option',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
